# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 03113d2d843be24582736a647b90a17145d076cae68c0931ab4656e2f09516200811167f27e0034dbef0372bbe1cc94ea51b3ecf39e90999086a002b57188dff

test:
  secret_key_base: 0573f9d48db116d58b89bf696143c25af02a192869a90923dc586baf77b4e3fb1307e86bdf95efe5c9dbb2e9552924310bfb422b398e10d4db005b146e78e98c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
